#!/bin/bash

CMD="$1"

if [[ ${CMD} = "start" ]]
then
 echo "Запуск демона CoLocolize SASSWatch..."
 screen -dmS CoLocolizeSASSWatch sass --watch ../css-src:../css --style compressed
fi


if [[ ${CMD} = "stop" ]]
then
 echo "Остановка демона CoLocolize SASSWatch..."
 screen -X -S CoLocolizeSASSWatch quit
fi

if [[ ${CMD} = "show" ]]
then
 echo "Вход в сессию CoLocolize SASSWatch..."
 screen -r CoLocolizeSASSWatch
fi